In [3]:
import pandas as pd

df = pd.read_csv("/Users/ilansarfati/Desktop/RAKUTEN/X_train_update.csv")
df_labels = pd.read_csv("/Users/ilansarfati/Desktop/RAKUTEN/Y_train_CVw08PX.csv")

print(df_labels["prdtypecode"].value_counts())
print(df_labels["prdtypecode"].nunique())  # Nombre de classes uniques

prdtypecode
2583    10209
1560     5073
1300     5045
2060     4993
2522     4989
1280     4870
2403     4774
2280     4760
1920     4303
1160     3953
1320     3241
10       3116
2705     2761
1140     2671
2582     2589
40       2508
2585     2496
1302     2491
1281     2070
50       1681
2462     1421
2905      872
60        832
2220      824
1301      807
1940      803
1180      764
Name: count, dtype: int64
27

In [6]:
import pandas as pd

df_X= pd.read_csv("/Users/ilansarfati/Desktop/RAKUTEN/X_train_update.csv", index_col=0)
df_Y= pd.read_csv("/Users/ilansarfati/Desktop/RAKUTEN/Y_train_CVw08PX.csv", index_col=0)

df_X[["designation", "description"]].head(5)

,designation,description
0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN
1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN
2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...
3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN
4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...

In [7]:
print(df_X["description"].isna().sum())
df_X[["designation", "description"]].sample(20)

29800

,designation,description
76526,Shin Sangoku Musou : Multi Raid Special (Impor...,NaN
56086,Poussette Gris 89 X 475 X 104 Cm,<p>Notre poussette de haute qualité et robuste...
58610,Maquette D'avion Wltoys Q808 Petit Ducted Avio...,WLtoysQ808 Small Ducted Aircraft 3D Flip Roll ...
39325,Cas Heureux Halloween Oreiller Linge Coussin S...,Heureux cas Halloween oreiller; Linge Coussin ...
74195,Lot De 2 Tomes Grand Galop N° 655 Et N°657,NaN
83482,Lot De 15 Jeux Xbox 360,NaN
61203,Accessoires Kit Pour Dji Pro Hélices Protector...,Accessoires Kit pour DJI Pro Hélices Protector...
17966,Angelique Et Le Roy Tomes 1 Et 2,NaN
23677,S4sassy Canard Coton Ocean Tablier De Cuisine ...,<p>* Ces tabliers colorés et élégants ocean vo...
40162,Simple Led Rectangulaire Applique Hôtel Salon ...,Led rectangulaire simple Applique Hôtel Salon ...
60826,3660 3300kvwaterproof Brushless Avec L'ensembl...,...
67799,Table Basse Carrée Bois Grisé - Barker,Superbe table basse moderne teinte bois grisé ...
5720,Textes Et Documents Pour La Classe N° 658 Du 0...,NaN
38347,Doudou Plat Winnie L'ourson Jaune Baby Pooh Di...,Doudou maison non fumeur et sans animaux
27707,Lot De 13 Livres D'histoire Scolaires,NaN
68198,Dogfight 1942 - Fire Over Africa (Extension Dl...,<br /> NOTE : Nécessite le jeu original <b>Dog...
21278,Hw7016 Amovible Grand Angle 0.3mp Caméra Hd Wi...,HW7016 détachable Grand Angle 0.3MP Caméra...
61372,Jjrc Jjpro X3 Rc Quadrirotor Drone Gps 2.4g 6c...,JJRC JJPRO X3 RC Quadrirotor Drone GPS 2.4G 6C...
2010,Lot De 2 Revue De La Franco Ancienne De 1948/1949,NaN
77303,Aries 550 6TP de Espa - Filtre à sable,Type de filtre : Filtre à sable Position de l...

In [9]:
df_X["text"] = df_X["designation"] + " " + df_X["description"].fillna("")
df_X[["designation", "description", "text"]].head(10)

,designation,description,text
0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,Olivia: Personalisiertes Notizbuch / 150 Seite...
1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...
2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,Grand Stylet Ergonomique Bleu Gamepad Nintendo...
3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,Peluche Donald - Europe - Disneyland 2000 (Mar...
4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,La Guerre Des Tuques Luc a des id&eacute;es de...
5,Afrique Contemporaine N° 212 Hiver 2004 - Doss...,NaN,Afrique Contemporaine N° 212 Hiver 2004 - Doss...
6,Christof E: Bildungsprozessen Auf Der Spur,NaN,Christof E: Bildungsprozessen Auf Der Spur
7,Conquérant Sept Cahier Couverture Polypro 240 ...,CONQUERANT CLASSIQUE Cahier 240 x 320 mm seyès...,Conquérant Sept Cahier Couverture Polypro 240 ...
8,Puzzle Scooby-Doo Avec Poster 2x35 Pieces,NaN,Puzzle Scooby-Doo Avec Poster 2x35 Pieces
9,Tente Pliante V3s5-Pro Pvc Blanc - 3 X 4m50 - ...,Tente pliante V3S5 Pro PVC 500 gr/m² - 3 x 4m5...,Tente Pliante V3s5-Pro Pvc Blanc - 3 X 4m50 - ...

In [10]:
from bs4 import BeautifulSoup

def clean_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

In [11]:
df_X["text"] = df_X["text"].apply(clean_html)

/var/folders/8g/nlbz_rzd6lz9xdj64s6mwp2m0000gn/T/ipykernel_26948/1450991660.py:4: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, "html.parser")

In [12]:
df_X["text"].head(10)

0    Olivia: Personalisiertes Notizbuch / 150 Seite...
1    Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...
2    Grand Stylet Ergonomique Bleu Gamepad Nintendo...
3    Peluche Donald - Europe - Disneyland 2000 (Mar...
4    La Guerre Des Tuques Luc a des idées de grande...
5    Afrique Contemporaine N° 212 Hiver 2004 - Doss...
6          Christof E: Bildungsprozessen Auf Der Spur
7    Conquérant Sept Cahier Couverture Polypro 240 ...
8           Puzzle Scooby-Doo Avec Poster 2x35 Pieces
9    Tente Pliante V3s5-Pro Pvc Blanc - 3 X 4m50 - ...
Name: text, dtype: object

In [13]:
df_X["text"] = df_X["text"].str.lower()

df_X["text"].head(10)

0    olivia: personalisiertes notizbuch / 150 seite...
1    journal des arts (le) n° 133 du 28/09/2001 - l...
2    grand stylet ergonomique bleu gamepad nintendo...
3    peluche donald - europe - disneyland 2000 (mar...
4    la guerre des tuques luc a des idées de grande...
5    afrique contemporaine n° 212 hiver 2004 - doss...
6          christof e: bildungsprozessen auf der spur
7    conquérant sept cahier couverture polypro 240 ...
8           puzzle scooby-doo avec poster 2x35 pieces
9    tente pliante v3s5-pro pvc blanc - 3 x 4m50 - ...
Name: text, dtype: object

In [17]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

stop_words = set(stopwords.words("french"))
print(stop_words)
len(stop_words)

{'me', 'à', 'ayantes', 'moi', 'aurons', 'leur', 'était', 'fusse', 'est', 'étions', 'aurions', 'étais', 'elle', 'de', 'soient', 'fus', 'vos', 'en', 'seras', 'seront', 'ils', 'que', 'eut', 'aurez', 'fussiez', 'mais', 'ont', 'nos', 'étaient', 'c', 'eussions', 'tes', 'aura', 'd', 'mes', 'fussent', 'même', 'êtes', 'aux', 'fût', 'aviez', 'ayons', 's', 'ces', 'eusse', 'aurait', 'étés', 'ses', 'mon', 'ayant', 'qu', 'ton', 'serai', 'soyez', 'y', 'serons', 'eus', 'seriez', 'sa', 'aient', 'n', 'toi', 'le', 'une', 'avais', 'ta', 'es', 'par', 'ai', 'votre', 'étant', 'sont', 'ne', 'son', 'serez', 'ma', 'ce', 'du', 'eussiez', 'aurai', 'avions', 'pour', 'étantes', 'eûmes', 'ayez', 'vous', 'furent', 'fut', 'la', 'fusses', 'te', 'avez', 'sois', 'je', 'été', 'étée', 'l', 'fûtes', 'étées', 'il', 'pas', 'auraient', 'avait', 'qui', 'soyons', 'étiez', 'auras', 'eusses', 'lui', 'serions', 'suis', 'eurent', 'avons', 'seraient', 'ayants', 'fussions', 'et', 'avaient', 'dans', 'nous', 'étants', 't', 'sera', 'un', 'aie', 'aies', 'serait', 'soit', 'eussent', 'au', 'se', 'eu', 'eues', 'j', 'serais', 'eue', 'sommes', 'ait', 'étante', 'les', 'eûtes', 'on', 'auront', 'aurais', 'sur', 'des', 'auriez', 'notre', 'tu', 'fûmes', 'm', 'eût', 'ayante', 'avec', 'ou', 'eux', 'as'}

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ilansarfati/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

157

In [18]:
def remove_stopwords(text):
    mots = text.split()
    mots_filtre =  [mot for mot in mots if mot not in stop_words]
    return " ".join(mots_filtre)

In [22]:
df_X["text"].apply(remove_stopwords)

0        olivia: personalisiertes notizbuch / 150 seite...
1        journal arts (le) n° 133 28/09/2001 - l'art ma...
2        grand stylet ergonomique bleu gamepad nintendo...
3        peluche donald - europe - disneyland 2000 (mar...
4        guerre tuques luc a idées grandeur. veut organ...
                               ...
84911                          the sims [ import anglais ]
84912    kit piscine acier nevada déco pierre ø 3.50m x...
84913    journal officiel republique francaise n° 46 15...
84914    table basse bois récupération massif base blan...
84915    gomme collection 2 gommes pinguin glace vert o...
Name: text, Length: 84916, dtype: object

In [23]:
import spacy
nlp = spacy.load("fr_core_news_sm")

def lemmatize(text):
    doc = nlp(text)
    lemmes = [token.lemma_ for token in doc]
    return " ".join(lemmes)

In [24]:
df_X["text"] = df_X["text"].apply(lemmatize)

In [26]:
df_X["text"].head(10)

0    olivia : personalisierte notizbuch / 150 seite...
1    journal de art ( le ) numéro 133 de 28/09/2001...
2    grand stylet ergonomique bleu gamepad nintendo...
3    peluche donald - europe - disneyland 2000 ( ma...
4    le guerre de tuque luc avoir un idée de grande...
5    afrique contemporain numéro 212 hiver 2004 - d...
6          christof e : bildungsprozessen auf der spur
7    conquérir sept cahier couverture polypro 240 x...
8           puzzle scooby - doo avec poster 2x35 piece
9    tente pliante v3s5-pro pvc blanc - 3 x 4m50 - ...
Name: text, dtype: object

In [27]:
df_X.to_csv("df_X_clean.csv")